# Generated by Django 5.2.7 on 2025-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschema',
            name='event_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventschema',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'wedding'), ('Conference', 'conference'), ('Birthday Party', 'birthday'), ('Corporate Retreat', 'corporate_retreat'), ('Product Launch', 'product_launch'), ('Seminar', 'seminar'), ('Networking Event', 'networking'), ('Charity Gala', 'charity_gala'), ('Fundraiser', 'fundraiser'), ('Trade Show', 'trade_show'), ('Concert', 'concert'), ('Festival', 'festival'), ('Sports Event', 'sports_event'), ('Workshop', 'workshop'), ('Award Ceremony', 'award_ceremony'), ('Team Building', 'team_building')], max_length=100),
        ),
    ]
