# Generated by Django 5.2.7 on 2025-10-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('isAccountVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('organization', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('International', 'International'), ('NGO', 'NGO')], max_length=50)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='user_app.userregmodel')),
            ],
        ),
    ]
