# Generated by Django 5.2.7 on 2025-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregmodel',
            name='phoneNumber',
            field=models.CharField(max_length=50),
        ),
    ]
