# Generated by Django 4.2.24 on 2025-10-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('wedding', 'wedding'), ('conference', 'conference'), ('birthday', 'birthday')], max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_start_time', models.DateTimeField()),
                ('event_end_time', models.DateTimeField()),
                ('event_attendees', models.IntegerField()),
                ('event_description', models.CharField(max_length=800)),
            ],
        ),
    ]
