# Generated by Django 4.2.24 on 2025-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=20)),
                ('event_start_time', models.DateField()),
                ('event_end_time', models.DateField()),
                ('event_description', models.TextField()),
                ('event_attendees', models.IntegerField()),
            ],
        ),
    ]
